# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-14 06:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='Title')),
                ('body', models.TextField(verbose_name='Article')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Created_Date')),
                ('last_modified_time', models.DateTimeField(auto_now=True, verbose_name='Modified_Time')),
                ('status', models.CharField(choices=[('d', 'Draft'), ('p', 'Published')], max_length=1, verbose_name='Status')),
                ('abstract', models.CharField(blank=True, help_text='可选，如若为空将摘取正文的前54个字符', max_length=54, null=True, verbose_name='Abstract')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='View_Num')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='Like_Num')),
                ('topped', models.BooleanField(default=False, verbose_name='Topped')),
            ],
            options={
                'ordering': ['-last_modified_time'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Cite_Name')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Created_Time')),
                ('last_modified_time', models.DateTimeField(auto_now=True, verbose_name='Modified_Time')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.Category', verbose_name='Cite'),
        ),
    ]
